# define programming language
language: go

# specify which go version should be tested against project
go:
  - "1.10"
  - "1.9"

before_script:
  # all .go files, excluding vendor/
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  # install linter
  - go get github.com/golang/lint/golint
  # install static analyzer/linter
  - go get honnef.co/go/tools/cmd/megacheck
  # install gocyclo
  - go get github.com/fzipp/gocyclo
  # install dep
  - go get -u github.com/golang/dep/cmd/dep
  # install dependencies
  - make dep

  # install goveralls
  - go get github.com/mattn/goveralls


script:
  # test gofmt
  - test -z $(gofmt -s -l $GO_FILES) 
  # run all tests
  - go test -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 9We7aRhpr5K1xgDEUMqkoj8GO11tmpmZVsjf7
  # run go vet
  - go vet ./...
  # "go vet on steroids" + linter
  - megacheck ./...
  # forbid code with huge functions
  - gocyclo -over 19 $GO_FILES
  # linter
  - golint -set_exit_status $(go list ./...)